### ISSUE TITLE
About the release date

### ISSUE THREAD

**Issue by ChoiDM** [BingkeZhu/Ind-2M#1]
Thank you for your amazing work.
I'm inspired by the proposed cutting-edge pretraining technique for industrial domain.

Do you mind if I ask you to announce the specific release date of Ind-2M dataset?
Your fine-grained dataset will definitely help the development of deep learning models for industrial fields.

Best regards,
Dongmin Choi.

**Comment by BingkeZhu** [comment]
Thank you for your attention. We have now open-sourced our Ind-2M dataset. If you have any questions, please reopen the issue and feel free to ask.
